name: CI-API

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

defaults:
  run:
    working-directory: api

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    services:
      db:
        image: postgres:13
        env:
          POSTGRES_USER: pr
          POSTGRES_PASSWORD: password
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
    - uses: actions/checkout@v2.4.0
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2.5.0
      with:
        node-version: ${{ matrix.node-version }}
        cache: yarn
        cache-dependency-path: api/yarn.lock
    - run: yarn install --frozen-lockfile
    - run: yarn lint
    - run: yarn prisma generate
    - run: yarn build
    - name: Run unit tests
      run: yarn test
    - run: yarn prisma migrate deploy
      env:
        DATABASE_URL: postgresql://pr:password@localhost:5432/pr
    - name: Run E2E tests
      run: yarn test:e2e
      env:
        DATABASE_URL: postgresql://pr:password@localhost:5432/pr
