name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    services:
      db:
        image: postgres:13
        env:
          POSTGRES_USER: pr
          POSTGRES_PASSWORD: password
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
    - uses: actions/checkout@v2.3.4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2.3.0
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install node modules
      uses: bahmutov/npm-install@v1
    - run: yarn api prisma generate
    - run: yarn api build
    - name: Run unit tests
      run: yarn api test
    - run: yarn api prisma migrate deploy
      env:
        DATABASE_URL: postgresql://pr:password@localhost:5432/pr
    - name: Run E2E tests
      run: yarn api test:e2e
      env:
        DATABASE_URL: postgresql://pr:password@localhost:5432/pr
    - run: yarn web build
